openapi: 3.0.3
info:
  title: Хлебная лавка
  description: Магазин хлебобулочных изделий
  version: 0.0.1
servers:
  - url: http://localhost:8080/bread-shop
tags:
  - name: positions
    description: методы для работы с позициями меню
  - name: purchases
    description: методы для работы с заказами
  - name: customers
    description: методы для работы с покупателями



components:
  schemas:
    Id:
      title: 'Id'
      type: integer
      format: int64
      example: 101
      description: ID объекта

    MenuModel:
      title: 'MenuModel'
      description: Модель для работы с позициями в меню
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
          example: Бублик
          description: Наименование позиции
        cost:
          type: number
          format: double
          example: 150.5
          description: Стоимость позиции

    PurchaseModel:
      title: 'PurchaseModel'
      description: Модель для работы с совершенными покупками
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        customerId:
          type: integer
          format: int64
          example: 101
          description: ID покупателя
        positionId:
          type: integer
          format: int64
          example: 101
          description: ID позиции в меню
        count:
          type: integer
          format: int64
          example: 2
          description: Количество покупаемых позиций
        sumCost:
          type: number
          format: double
          example: 200.45
          description: Итоговая стоимость
        datePurchase:
          type: string
          format: date
          example: 2024-11-04 12:00:00
          description: Дата совершения покупки

    CustomerModel:
      title: 'CustomerModel'
      description: Модель для работы с покупателями
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          type: string
          example: Человечков Человечек
          description: Имя покупателя
        sumCost:
          type: number
          format: double
          example: 200.45
          description: Общая сумма купленных за все время позиций


    UpdateCostItemRequest:
      title: 'UpdateCostItemRequest'
      description: Запрос для обновления позиции в меню
      type: object
      properties:
        cost:
          type: number
          format: double
          example: 150.5
          description: Стоимость позиции

    AddItemRequest:
      title: 'AddItemRequest'
      description: Запрос на создание новой позиции
      type: object
      properties:
        name:
          type: string
          example: Бублик
          description: Наименование позиции
        cost:
          type: number
          format: double
          example: 150.5
          description: Стоимость позиции

    AddPurchaseRequest:
      title: 'AddPurchaseRequest'
      description: Запрос на совершение покупки
      type: object
      properties:
        customerId:
          $ref: '#/components/schemas/Id'
        positionId:
          $ref: '#/components/schemas/Id'
        count:
          type: integer
          format: int64
          example: 2
          description: Количество покупаемых позиций

    AddCustomerRequest:
      title: 'AddCustomerRequest'
      description: Запрос для добавления нового покупателя
      type: object
      properties:
        name:
          type: string
          example: Человечков Человечек
          description: Имя покупателя

    ChangeNameCustomerRequest:
      title: 'ChangeNameCustomerRequest'
      description: Модель для изменения имени покупателя
      type: object
      properties:
        name:
          type: string
          example: Человечков Человечек
          description: Имя покупателя


paths:
  /positions:
    get:
      tags:
        - positions
      summary: Получение всех изделий в меню
      description: Получение всех изделий в меню
      operationId: positions
      responses:
        '200':
          description: Все изделия в меню успешно получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос')
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

    post:
      tags:
        - positions
      summary: Добавление новой позиции в меню
      description: Добавление новой позиции в меню
      operationId: addPosition
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemRequest'
      responses:
        '200':
          description: Новая позиция добавлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

  /positions/{id}:
    get:
      tags:
        - positions
      summary: Получение позиции в меню
      description: Получение позиции в меню
      operationId: getPosition
      parameters:
        - name: id
          in: query
          required: true
          description: Уникальный идентификатор позиции
          schema:
            $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: Позиция из меню успешно получена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос')
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

    patch:
      tags:
        - positions
      summary: Изменение стоимости позиции
      description: Изменение стоимости позиции
      operationId: updatePositionCost
      parameters:
        - name: id
          in: query
          required: true
          description: Уникальный идентификатор позиции
          schema:
            $ref: '#/components/schemas/Id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCostItemRequest'
      responses:
        '200':
          description: Стоимость позиии успешна изменена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

    put:
      tags:
        - positions
      summary: Изменение позиции
      description: Изменение позиции
      operationId: changePosition
      parameters:
        - name: id
          in: query
          required: true
          description: Уникальный идентификатор позиции
          schema:
            $ref: '#/components/schemas/Id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuModel'
      responses:
        '200':
          description: Позиция успешна изменена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')


  /purchases:
    get:
      tags:
        - purchases
      summary: Получение всех покупок
      description: Получение всех покупок
      operationId: getPurchaseList
      responses:
        '200':
          description: Покупки получены успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

    post:
      tags:
        - purchases
      summary: Совершение покупки
      description: Совершение покупки
      operationId: addPurchase
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPurchaseRequest'
      responses:
        '200':
          description: Покупка совершена успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

  /purchases/{id}:
    get:
      tags:
        - purchases
      summary: Получение покупки
      description: Получение покупки
      operationId: addPurchase
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPurchaseRequest'
      responses:
        '200':
          description: Покупка совершена успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')


  /customers:
    get:
      tags:
        - customers
      summary: Получение всех покупателей
      description: Получение всех покупателей
      operationId: getCustomerList
      responses:
        '200':
          description: Все покупатели успешно получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

    post:
      tags:
        - customers
      summary: Добавление нового покупателя
      description: Добавление нового покупателя
      operationId: addCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCustomerRequest'
      responses:
        '200':
          description: Новый покупатель успешно добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')


  /customers/{id}:
    get:
      tags:
        - customers
      summary: Получение покупателя
      description: Получение покупателя
      operationId: getCustomer
      parameters:
        - name: id
          in: query
          required: true
          description: Уникальный идентификатор покупателя
          schema:
            $ref: '#/components/schemas/Id'
      responses:
        '200':
          description: Покупатели успешно получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')

    patch:
      tags:
        - customers
      summary: Изменение имени покупателя
      description: Изменение имени покупателя
      operationId: changeCustomerName
      parameters:
        - name: id
          in: query
          required: true
          description: Уникальный идентификатор покупателя
          schema:
            $ref: '#/components/schemas/Id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeNameCustomerRequest'
      responses:
        '200':
          description: Имя покупателя изменено успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerModel'
        '400':
          description: 400 Bad Request ('неправильный, некорректный запрос)
        '404':
          description: 404 Not Found ('не найдено')
        '500':
          description: Internal Server Error ('внутрення ошибка сервера')
